"""
This script's objective is to be an example on how to use the API and interact with the solution
"""

import requests


BASE_URL = "http://localhost:5000"

# 1. get all available tickers for optimization
avail_tickers_url = f"{BASE_URL}/available_tickers"
avail_tickers_r = requests.get(avail_tickers_url)
stocks = eval(avail_tickers_r.text)["available_stocks"]

# 2. select the first 5 stocks randomly for optimization
stocks_opt = stocks[:5]

# 3. parse stocks from list to string as API is expecting
stocks_opt_parsed = ", ".join([str(stock) for stock in stocks_opt])

# 4. send optimization request
opt_request_url = f"{BASE_URL}/portfolio_optimize"
tickers = {"tickers": stocks_opt_parsed}

opt_request_r = requests.post(opt_request_url, json=tickers)

breakpoint()

# 5. retrieve uuid generated by the optimization request
parsed_r = eval(opt_request_r.text)

breakpoint()
