"""
This script's objective is to be an example on how to use the API and interact with the solution
"""

import requests
from time import sleep


BASE_URL = "http://localhost:5000"

# 1. get all available tickers for optimization
avail_tickers_url = f"{BASE_URL}/available_tickers"
avail_tickers_r = requests.get(avail_tickers_url)
stocks = eval(avail_tickers_r.text)["available_stocks"]

# 2. select the first N stocks randomly for optimization
stocks_opt = stocks[:30]

# 3. parse stocks from list to string as API is expecting
stocks_opt_parsed = ", ".join([str(stock) for stock in stocks_opt])

# 4. send optimization request
opt_request_url = f"{BASE_URL}/portfolio_optimize"
tickers = {"tickers": stocks_opt_parsed}

opt_request_r = requests.post(opt_request_url, json=tickers)

# 5. retrieve uuid generated by the optimization request
parsed_r = eval(opt_request_r.text)

if (
    parsed_r["optimization_status"] == "started"
):  # it means the optimization has started, then get uuid
    uuid = parsed_r["uuid"]

else:
    assert False, "There's an error during optimization start"

# 6. check results
opt_results_url = f"{BASE_URL}/optimization_results"
_uuid = {"uuid": uuid}

results_status = "running"

while results_status != "finished":
    print("Waiting for API results...")
    sleep(5)
    opt_results_r = requests.post(opt_results_url, json=_uuid)
    results_parsed = eval(opt_results_r.text)
    results_status = results_parsed["optimization_status"]


print(results_parsed["results"])
