CREATE DATABASE aux;
GRANT ALL PRIVILEGES ON DATABASE aux TO gpalazzo;

CREATE DATABASE raw;
GRANT ALL PRIVILEGES ON DATABASE raw TO gpalazzo;

CREATE DATABASE intm;
GRANT ALL PRIVILEGES ON DATABASE intm TO gpalazzo;

CREATE DATABASE prm;
GRANT ALL PRIVILEGES ON DATABASE prm TO gpalazzo;

CREATE DATABASE fte;
GRANT ALL PRIVILEGES ON DATABASE fte TO gpalazzo;

CREATE DATABASE mi;
GRANT ALL PRIVILEGES ON DATABASE mi TO gpalazzo;