CREATE DATABASE raw;
GRANT ALL PRIVILEGES ON DATABASE raw TO gpalazzo;

CREATE DATABASE prm;
GRANT ALL PRIVILEGES ON DATABASE prm TO gpalazzo;

CREATE DATABASE fte;
GRANT ALL PRIVILEGES ON DATABASE fte TO gpalazzo;