[tool.poetry]
name = "portfolio_opt_api"
version = "0.1.0"
description = ""
authors = ["Guilherme Palazzo <palazzoeng1@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7.*"

# GENERAL MAJOR DEPS

[tool.poetry.dev-dependencies]
black = "^21.7b0"
